name: Deploy IaC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply (Citrix)
        working-directory: ./citrix/terraform
        env:
          TF_VAR_netscaler_password: ${{ secrets.NETSCALER_PASSWORD }}
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve

      - name: Terraform Init & Apply (NetScaler)
        working-directory: ./netscaler/terraform
        env:
          TF_VAR_netscaler_password: ${{ secrets.NETSCALER_PASSWORD }}
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
